{
 "title": "Nodejs Express Monitoring",
 "description": "Nodejs Express Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Response Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(status, le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{status}} (95%)"
    },
    {
     "expr": "histogram_quantile(1, sum by(status, le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{status}} (100%)"
    }
   ]
  },
  {
   "title": "QUERIES PER SEC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "CUSTOMER LIST COUNT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(method) (rate(http_request_duration_seconds_bucket{path=\"/api/customers\", method=\"GET\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "TOTAL REQUESTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVERAGE RESPONSE TIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_count{status_code=~\"2..|304\"}[1m])) * 100) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TIMEOUTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(http_request_duration_seconds_bucket{le=\"10\"}[$__interval])) - sum(count_over_time(http_request_duration_seconds_bucket{le=\"1.5\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx ERRORS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(http_request_duration_seconds_count{status_code=~\"4..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx ERRORS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(http_request_duration_seconds_count{status_code=~\"5..\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CANCLED REQUESTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(http_request_duration_seconds_bucket{le=\"10\"}[$__interval])) - sum(count_over_time(http_request_duration_seconds_bucket{le=\"1.5\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESS vs FAIL LOGIN",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(status_code) (http_request_duration_seconds_bucket{path=\"/api/auth/login\", method=\"POST\", status_code=~\"2..\"}),\n  \"result\", \"success\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  sum by(status_code) (http_request_duration_seconds_bucket{path=\"/api/auth/login\", method=\"POST\", status_code!~\"2..\"}),\n  \"result\", \"fail\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESSFUL CUSOTMER CREATION COUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(http_request_duration_seconds_bucket{path=\"/api/customers\", method=\"POST\", status_code=\"201\", le=\"+Inf\", instance=\"localhost:3000\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESSFUL TECHNICAL CONFIG CREATION COUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(http_request_duration_seconds_bucket{path=\"/api/customer-technical/config\", status_code=\"201\", method=\"POST\", le=\"+Inf\", instance=\"localhost:3000\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESSFUL SUBSCRIPTION CREATION COUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(http_request_duration_seconds_bucket{path=\"/api/customers/#val/subscription/add\", status_code=\"201\", method=\"POST\", le=\"+Inf\", instance=\"localhost:3000\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AUTHENTICATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "AUTH PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/auth/login\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AUTH PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg by(status_code) (avg_over_time(http_request_duration_seconds_bucket{path=\"/api/auth/me\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CUSTOMER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CUSTOMER PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CUSTOMER TECHNICAL CONFIG PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customer-technical/config\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CUSTOMER ADD SUBSCRIPTION PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customers/#val/subscription/add\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CUSTOMER TECHNICAL INFO STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customer-technical/info/#val\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EACH CUSTOMER TECHNICAL CONFIG FETCH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customer-technical/config/#val\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EACH CUSTOMER TECHNICAL INFO  FETCH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customer-technical/info/#val\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET EACH CUSTOMER SUBSCRIPTION DETAIL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customers/#val/subscription/detail/#val\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET EACH CUSTOMER SUBSCRIPTION LIST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customers/#val/subscription/list/byCustomer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CUSTOMER SEARCH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customers/namesbySearch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CUSTOMER STATUS UPDATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/customers/status/update\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "INVOICE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "INVOICE PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/invoices\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LIST EACH INVOICE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/invoices/invoice-number/#val\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "INTERNET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "INTERNET ITEM FETCH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "avg by(status_code) (avg_over_time(http_request_duration_seconds_bucket{path=\"/api/internets/#val\", le=\"+Inf\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LIST INTERNET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "avg by(status_code) (avg_over_time(http_request_duration_seconds_bucket{path=\"/api/internets/get/all\", le=\"+Inf\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ROUTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "ROUTER PATH STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/routers\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LIST EACH ROUTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/routers/#val\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LIST ROUTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/routers/list\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROUTER QUEUE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "avg by(status_code) (http_request_duration_seconds_bucket{path=\"/api/routers/#val/router-queue\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "BULL MQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "BULL API QUEUES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum by(status_code) (sum_over_time(http_request_duration_seconds_bucket{path=\"/bull-ui/api/queues\", le=\"+Inf\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRANSITION QUEUE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "sum by(status_code) (sum_over_time(http_request_duration_seconds_bucket{path=\"/bull-ui/queue/transaction-queue\", le=\"+Inf\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MIKROTIK SQ QUEUE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "sum by(status_code) (sum_over_time(http_request_duration_seconds_bucket{path=\"/bull-ui/queue/mikrotik-sq-queue\", le=\"+Inf\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RYZE SORTING QUEUE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "sum by(status_code) (sum_over_time(http_request_duration_seconds_bucket{path=\"/bull-ui/queue/ryze-sorting-queue\", le=\"+Inf\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}